### ISSUE TITLE
Add ability to use custom Google font

### ISSUE THREAD

**Issue by F1LT3R** [rreusser/the-old-github-font#11]
It would be great to have an option in the dropdown to use a custom google font url.

![screen shot 2016-07-13 at 2 56 06 pm](https://cloud.githubusercontent.com/assets/1218446/16815943/003af5bc-490a-11e6-87cd-f3e1980af4e8.png)

**Comment by rreusser** [comment]
Thanks for the feedback! At the moment, I'd probably consider that out of the scope of this project. I think a better fit might be Stylish or user-styles which let you directly define and share site-targeted stylesheets (I'm only reciting those names based on other suggestions; I haven't used them). So at risk of being dismissive I'll close this issue, but please don't think I don't appreciate the feedback and suggestion!
