### ISSUE TITLE
old colors 

### ISSUE THREAD

**Issue by stevermeister** [rreusser/the-old-github-font#12]
could you please make the same for colors please ?

**Comment by rreusser** [comment]
A good suggestion, but life has a way of getting busy, so that since making the extension, I've decided to entrust more of my aesthetic decisions to the wonderful, talented people at github. 😄

**Comment by stevermeister** [comment]
ok, I made userscript for it. 
https://github.com/stevermeister/userscripts/blob/master/github-old-colors.user.js
can't live with this new acid-blue colors :)

**Comment by rreusser** [comment]
Awesome! Oh wow. Hadn't been at a computer. Yeah, it's very blue!
