### ISSUE TITLE
GitHub Enterprise

### ISSUE THREAD

**Issue by passsy** [rreusser/the-old-github-font#4]
Add an option to add GitHub enterprise urls

**Comment by rreusser** [comment]
Hmm… I don't use github enterprise. Could you clarify the change necessary for it to work there?

**Comment by rreusser** [comment]
Looks like maybe just applying it to `enterprise.github.com`, right?

**Comment by passsy** [comment]
no the url can be anything. i.e. `https://svnwascooltoo.mycompany.com`

**Comment by Gamecrafter** [comment]
I don't think this can be hard-coded into the extension. Perhaps add a feature where users can add custom URLs?

**Comment by rreusser** [comment]
Ah, makes sense. Sounds like a very sensible thing, and I would gladly accept a PR for accomplishing this by whatever means make sense (a text field to whitelist domains?), but it goes a bit beyond my interest and time-availability at the moment.

**Comment by anishathalye** [comment]
It's pretty easy for people to download [manifest.json](https://github.com/rreusser/the-old-github-font/blob/209ca8dc6b0b9372a36d897c98ebe40b4d150460/extension/manifest.json), add their URL to [matches](https://github.com/rreusser/the-old-github-font/blob/209ca8dc6b0b9372a36d897c98ebe40b4d150460/extension/manifest.json#L18), and [install the unpacked extension](https://developer.chrome.com/extensions/getstarted#unpacked).

**Comment by rreusser** [comment]
@anishathalye only downside: does it periodically warn you against unpacked extensions being potentially harmful? Or is that a one-time warning?

**Comment by rreusser** [comment]
@passsy — #7 suggests an alternate approach that may better suit your needs: install the [stylish](https://chrome.google.com/webstore/detail/stylish/fjnbnpbmkenffdnngjfgmeleoegfcffe?hl=en) extension and then you can customize the CSS and domain as much as desired. 👍🏼

**Comment by passsy** [comment]
works
